updated private ui docker file and ci/cd pipelines

diff --git a/.github/workflows/ci-private-portal-ui.yaml b/.github/workflows/ci-private-portal-ui.yaml
--- a/.github/workflows/ci-private-portal-ui.yaml
+++ b/.github/workflows/ci-private-portal-ui.yaml
@@ -27,18 +27,21 @@ jobs:
         with:
           node-version: "22.x"
 
-      - name: Install and build shared-ui
-        run: |
-          cd shared-workspace
-          npm install
-          npx ng build shared-ui
-
       - name: Install Dependencies
         run: |
           cd dfa/src/UI/embc-dfa
           npm install --ignore-scripts
           if [ $? -ne 0 ]; then
             echo "::error::Failed to install npm packages"
+            exit 1
+          fi
+
+      - name: Install Dependencies for shared-workspace
+        run: |
+          cd shared-workspace
+          npm install --ignore-scripts
+          if [ $? -ne 0 ]; then
+            echo "::error::Failed to install npm packages in shared-workspace"
             exit 1
           fi
 
